### ISSUE TITLE
$.merge could not cast Integer to Long

### ISSUE THREAD

**Issue by leeaee** [osglworks/java-tool#176]
Code example:

UserAddress object:
```java
public class UserAddress implements SimpleBean {

    public Long userId;
    public String name;
    public String phone;
    ...
```

Map code:
```java
    Map<String, Object> map = new HashMap<>();
    map.put("userId", 1);
    UserAddress ua = new UserAddress();
    ua.userId = 2L;
    $.merge(map).to(ua);
```
Throw exception:
```log
Exception in thread "main" org.osgl.exception.MappingException: Type mismatch copy source [java.lang.Integer] to field[userId|java.lang.Long]
	at org.osgl.util.DataMapper.mappingError(DataMapper.java:1306)
	at org.osgl.util.DataMapper.logError(DataMapper.java:1253)
	at org.osgl.util.DataMapper.toPojo(DataMapper.java:973)
	at org.osgl.util.DataMapper.doMapping(DataMapper.java:647)
	at org.osgl.util.DataMapper.<init>(DataMapper.java:594)
	at org.osgl.Lang$_MappingStage.to(Lang.java:10179)
```

**Comment by greenlaw110** [comment]
`$.merge` doesn't do type conversion. Please try `$.mergeMap()` instead
