### ISSUE TITLE
Make mapping framework support `C.Range`

### ISSUE THREAD

**Issue by greenlaw110** [osglworks/java-tool#92]
as subject

**Comment by greenlaw110** [comment]
it is already possible to copy data from range to other data structure but unlikely to be copied from other data structure. 

What we need to do is to unlock copy from one container type to another even when semantic is not MAPPING, which is covered by #94

**Comment by greenlaw110** [comment]
Turns out this is not supported yet.

Source code:

```java
return $.copy(C.range(start, end)).to(new int[end - start]);
```

Got exception:

```
org.osgl.exception.MappingException: Cannot map source[org.osgl.util.LazyRange] into array or collection
	at org.osgl.util.DataMapper.mappingError(DataMapper.java:1043)
	at org.osgl.util.DataMapper.logError(DataMapper.java:993)
	at org.osgl.util.DataMapper.toArrayOrCollection(DataMapper.java:623)
	at org.osgl.util.DataMapper.doMapping(DataMapper.java:588)
	at org.osgl.util.DataMapper.<init>(DataMapper.java:542)
	at org.osgl.Lang$_MappingStage.to(Lang.java:9556)
```
