### ISSUE TITLE
Mapping error caused by `ConcurrentModificationException`

### ISSUE THREAD

**Issue by greenlaw110** [osglworks/java-tool#96]
Java source:

```java
    public static class Bar {
        private boolean flag = $.random(true, false);
        private double d = N.randDouble();
        private int[] ia = $.copy(C.range(0, 30)).to(new int[30]);
    }

    public static class Foo {
        private int id = N.randInt();
        private String name = S.random();
        private Map<String, Bar> map = C.Map("a", new Bar(), "b", new Bar());
    }

    private Foo source = new Foo();
    private Foo target = new Foo();


    @Test
    public void testOsglCopy() throws Exception {
        $.copy(source).to(target);
    }
```

Error log
```
org.osgl.exception.MappingException: Error mapping from benchmark.BeanCopyBenchmark$Foo to benchmark.BeanCopyBenchmark$Foo

	at org.osgl.util.DataMapper.mappingError(DataMapper.java:940)
	at org.osgl.util.DataMapper.logError(DataMapper.java:882)
	at org.osgl.util.DataMapper.doMapping(DataMapper.java:530)
	at org.osgl.util.DataMapper.<init>(DataMapper.java:475)
	at org.osgl.Lang$_MappingStage.to(Lang.java:8852)
	at benchmark.BeanCopyBenchmark.testOsglCopy(BeanCopyBenchmark.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.carrotsearch.junitbenchmarks.BenchmarkStatement$BaseEvaluator.evaluateInternally(BenchmarkStatement.java:104)
	at com.carrotsearch.junitbenchmarks.BenchmarkStatement$SequentialEvaluator.evaluate(BenchmarkStatement.java:148)
	at com.carrotsearch.junitbenchmarks.BenchmarkStatement.evaluate(BenchmarkStatement.java:389)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.osgl.util.DataMapper.mapToPojo(DataMapper.java:705)
	at org.osgl.util.DataMapper.doMapping(DataMapper.java:524)
	... 29 more
```

**Comment by greenlaw110** [comment]
oops, this is caused by a bug in #95
